slam_toolbox:
  ros__parameters:
    use_sim_time: false

    map_frame: map
    odom_frame: odom
    base_frame: base_link

    scan_topic: /scan
    mode: mapping

    resolution: 0.05
    max_laser_range: 10.0

    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    publish_tf: true
    transform_publish_period: 0.02
    tf_buffer_duration: 30.0
