slam_toolbox:
  ros__parameters:
    use_sim_time: false

    map_frame: map
    odom_frame: odom
    base_frame: base_laser

    scan_topic: /scan
    mode: mapping

    resolution: 0.05
    max_laser_range: 10.0

    # 让它更容易更新（你现在 0.1 太大）
    minimum_travel_distance: 0.02
    minimum_travel_heading: 0.02

    # 关键：减少 TF 来不及导致的丢帧
    scan_queue_size: 200
    transform_timeout: 1.0
    tf_buffer_duration: 120.0

    # 发布 map->odom TF
    publish_tf: true
    transform_publish_period: 0.05
