slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # è¿™é‡Œæ˜¯å…³é”®ä¸‰è¡Œ ğŸ‘‡
    map_frame: map
    odom_frame: base_link
    base_frame: base_link

    scan_topic: /scan
    mode: mapping

    # ä¸‹é¢æ˜¯ä¸€äº›å¸¸ç”¨é»˜è®¤å‚æ•°ï¼Œå¯ä»¥å…ˆä¸ç”¨æ”¹
    resolution: 0.05
    max_laser_range: 10.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    transform_publish_period: 0.02
    publish_tf: true
    tf_buffer_duration: 30.0
