slam_toolbox:
  ros__parameters:
    use_sim_time: false

    map_frame: map
    odom_frame: odom
    base_frame: base_link   # 强烈建议用 base_link，不用 base_laser

    scan_topic: /scan
    mode: mapping

    resolution: 0.05
    max_laser_range: 10.0

    # 不要太小，避免抖动
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    # 地图更新频率（稳定）
    map_update_interval: 1.0
    throttle_scans: 1

    # TF
    transform_timeout: 0.5
    tf_buffer_duration: 60.0

    publish_tf: true
    transform_publish_period: 0.05
