CLaserOdometry2DNode:
  ros__parameters:
    laser_scan_topic: /scan
    odom_topic: /odom_rf2o
    odom_frame_id: odom
    base_frame_id: base_laser
    publish_tf: false

    init_pose_from_topic: ""
